id = "novahub"
name = "NovaHub"
description = "The open source coding agent."
version = "1.1.48"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/novahub"

[agent_servers.novahub]
name = "NovaHub"
icon = "./icons/novahub.svg"

[agent_servers.novahub.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/novahub/releases/download/v1.1.48/novahub-darwin-arm64.zip"
cmd = "./novahub"
args = ["acp"]

[agent_servers.novahub.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/novahub/releases/download/v1.1.48/novahub-darwin-x64.zip"
cmd = "./novahub"
args = ["acp"]

[agent_servers.novahub.targets.linux-aarch64]
archive = "https://github.com/anomalyco/novahub/releases/download/v1.1.48/novahub-linux-arm64.tar.gz"
cmd = "./novahub"
args = ["acp"]

[agent_servers.novahub.targets.linux-x86_64]
archive = "https://github.com/anomalyco/novahub/releases/download/v1.1.48/novahub-linux-x64.tar.gz"
cmd = "./novahub"
args = ["acp"]

[agent_servers.novahub.targets.windows-x86_64]
archive = "https://github.com/anomalyco/novahub/releases/download/v1.1.48/novahub-windows-x64.zip"
cmd = "./novahub.exe"
args = ["acp"]
