name: novahub

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  novahub:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /novahub') ||
      startsWith(github.event.comment.body, '/novahub')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run novahub
        uses: anomalyco/novahub/github@latest
        env:
          NOVAHUB_API_KEY: ${{ secrets.NOVAHUB_API_KEY }}
          NOVAHUB_PERMISSION: '{"bash": "deny"}'
        with:
          model: novahub/claude-opus-4-5
